### ISSUE TITLE
Removal Candidate

### ISSUE THREAD

**Issue by Adurol** [KaOS-Community-Packages/cadaver#1]
This Package will be removed in 7 days from KCP.

Reason: **[Blind copy](https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/cadaver&id=c9269515a8760ba176dd3e83e5994944590d7288) and Unmaintained**

Please see also: [Using KaOS Community Packages](https://kaosx.us/phpBB3/viewtopic.php?f=12&t=145)

**Comment by bvaudour** [comment]
No cadaver isn’t a blind copy. Entirely made manually :) 
But indeed, there’s no release anymore (but I don’t know other functional webdav cli).

**Comment by Adurol** [comment]
If it's still used and you are willing to maintain it I see no reason to remove the PKGBUILD from in KCP.
That cadaver itself isn't the freshest is not a KCP-related problem. If cadaver does the job for you, even if it's old, I gladly let it stay in KCP.

**Comment by Adurol** [comment]
Still removal candidate:

Reason: **Broken**
`==> ERROR: A failure occurred in build().`

**Comment by bvaudour** [comment]
It should be OK now.

**Comment by Adurol** [comment]
I got it to build here too now and will there close the issue.
Thanks for your work!
